### ISSUE TITLE
Found issue with the sampling of documents on IMT

### ISSUE THREAD

**Issue by thgiannos** [IntelCompH2020/domain_classification#16]
The n_samples parameter is not used as a number for some reason resulting in an error when calling the sample task.

What I did locally is change the line /src/task_manager.py:1991
from
self.sample_documents(sampler, fmt="json", n_samples=n_samples)
to
self.sample_documents(sampler, fmt="json", n_samples=int(n_samples))

and it seems to work correctly now. If you think this solution is good enough maybe you can include it in a new release

**Comment by Orieus** [comment]
Fixed in new release v3.5 (https://github.com/IntelCompH2020/domain_classification/releases/tag/v3.5)

the solution 

    self.sample_documents(sampler, fmt="json", n_samples=int(n_samples))

is fine, but it could raise an error when n_samples was None. I have changed the default value and explicty stated n_samples as int

   def on_sample(self, sampler: str = "", n_samples: int = -1)

The conversion to integers should be done automatically by run_dc_task.py
